apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  VITE_API_BASE_URL: http://103.159.50.232:31469
  VITE_IMAGE_URL: http://103.159.50.232:31469/api/ImageUpload/get/
  config.js: |
    window.VITE_API_BASE_URL = "http://103.159.50.232:31469";
    window.VITE_IMAGE_URL = "http://103.159.50.232:31469/api/ImageUpload/get/";