root@ctr1253594:/home/backend-sach# cat secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  connection: "Server=db12651.public.databaseasp.net; Database=db12651; User Id=db12651; Password=5Xe_w2?CS=a3; Encrypt=True; TrustServerCertificate=True; MultipleActiveResultSets=True;"
