apiVersion: v1
kind: Service
metadata:
  name: backend-sach-service
spec:
  type: LoadBalancer
  selector:
    app: backend-sach
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31469